### ISSUE TITLE
error in qr.coef(qr(fm), y = alm) when running MDCox.R

### ISSUE THREAD

**Issue by ghost** [lianyh/MultiDCoX#1]
Hey everyone,

I tried to run the MultiDCoX scripts on my MacBook Pro (R version 3.3.2 -- "Sincere Pumpkin Patch") with the example data. The preprocessing worked fine but I encountered the following when running:

Rscript MDCoX.R TESTOUT/processedSampleAttributeMDCX.txt TESTOUT/processedExpressionMDCX.txt TESTOUT/processedGroupsMDCX.txt TESTOUT/

Warning:
In as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2018c.1.0/zoneinfo/Europe/Berlin'
[1] "START"
Error in qr.coef(qr(fm), y = alm) : 
  'qr' and 'y' must have the equal number of rows
stopped

As I used the example data, I am a bit confused why I get this message. I could not figure out what is causing this error. Could you please help me?

Klebsi

**Comment by lianyh** [comment]
Hi,

I have updated the readme file, could you re-run it again?

thanks.
